version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 5000

actions:
  generate_dataset:
    run: > 
      ehrql:v1 generate-dataset analysis/dataset_definition_dx_to_med_time.py
      --output output/adhd_dataset.csv.gz
    outputs:
      highly_sensitive:
        adhd_dataset: output/adhd_dataset.csv.gz

  generate_output_table:
    run: python:v2 python analysis/calculate_time_diff_from_dx_to_med.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        table1: output/adhd_dia_med_gap_weeks.csv
  
  generate_adhd_prevalence:
    run: > 
      ehrql:v1 generate-measures analysis/measures_definition.py 
      --output output/adhd_prevalence.csv
    outputs:
      moderately_sensitive:
        measure: output/adhd_prevalence.csv

  ill_posed:
    run: > 
      ehrql:v1 generate-dataset analysis/ill_posed_script.py
      --output output/ill_posed_output.csv
    outputs:
      highly_sensitive:
        measure: output/ill_posed_output.csv
