version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 5000

actions:
  generate_dataset:
    run: > 
      ehrql:v1 generate-dataset analysis/dataset_definition_core.py 
      --output output/full_dataset_test.csv.gz
    outputs:
      highly_sensitive:
        adhd_dataset: output/adhd_dataset.csv.gz
  
  generate_charts:
    run: python:v2 python analysis/report.py
    needs: [generate_dataset_full]
    outputs:
      moderately_sensitive:
        table1: output/results_saved.csv